# Generated by Django 4.2.13 on 2026-05-25 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1 - Direct'), ('scope2_lb', 'Scope 2 - Location-Based'), ('scope2_mb', 'Scope 2 - Market-Based'), ('scope3', 'Scope 3 - Value Chain')], max_length=10)),
                ('category', models.CharField(choices=[('fuel_stationary', 'Stationary Combustion (Fuel)'), ('fuel_mobile', 'Mobile Combustion (Fuel)'), ('electricity', 'Purchased Electricity'), ('business_travel_air', 'Business Travel - Air'), ('business_travel_hotel', 'Business Travel - Hotel'), ('business_travel_ground', 'Business Travel - Ground Transport'), ('procurement', 'Procurement / Purchased Goods')], max_length=40)),
                ('quantity_kg_co2e', models.DecimalField(decimal_places=4, max_digits=18)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('source_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('source_unit', models.CharField(blank=True, max_length=50)),
                ('source_date_raw', models.CharField(blank=True, help_text='Original date string from source', max_length=100)),
                ('source_row_id', models.CharField(blank=True, help_text='Row identifier in source file', max_length=200)),
                ('source_extra', models.JSONField(blank=True, default=dict, help_text='Additional fields from source not mapped to schema')),
                ('emission_factor_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=100)),
                ('emission_factor_source', models.CharField(blank=True, help_text='e.g. DEFRA 2023, EPA eGRID 2022', max_length=200)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit'), ('flagged', 'Flagged - Needs Attention')], default='pending_review', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-period_start', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_flat_file', 'SAP Flat File (IDoc/IDOC)'), ('utility_csv', 'Utility Portal CSV'), ('travel_csv', 'Corporate Travel CSV')], max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('source_file_name', models.CharField(blank=True, max_length=500)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='ingestion/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial (some rows failed)')], default='pending', max_length=20)),
                ('row_count_total', models.IntegerField(default=0)),
                ('row_count_ok', models.IntegerField(default=0)),
                ('row_count_failed', models.IntegerField(default=0)),
                ('row_count_suspicious', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
                ('processing_notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='emissions.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_plant_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('grid_region', models.CharField(blank=True, help_text='For electricity emission factors', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='emissions.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'sap_plant_code')},
            },
        ),
        migrations.CreateModel(
            name='EmissionRecordEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['-edited_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='emissions.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='emissions.facilitylookup'),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.tenant'),
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('analyst', 'Analyst'), ('admin', 'Admin'), ('auditor', 'Auditor')], default='analyst', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='emissions.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'tenant')},
            },
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'status'], name='emissions_e_tenant__5a7e62_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope', 'period_start'], name='emissions_e_tenant__d14736_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['batch'], name='emissions_e_batch_i_f2aa5a_idx'),
        ),
    ]
